### PR TITLE
Use bioimageio.spec to validate ImJoy collection in GH workflow

### PR DESCRIPTION
**Pull request by FynnBe**
cc @oeway

### CODE REVIEW

**Comment by oeway** [comment]
@FynnBe Great! Thanks!

Do we know more info about this error: https://github.com/imjoy-team/bioimage-io-models/runs/6306914515?check_suite_focus=true#step:4:24

**Comment by FynnBe** [comment]
> Do we know more info about this error: https://github.com/imjoy-team/bioimage-io-models/runs/6306914515?check_suite_focus=true#step:4:24

Hey, that was related to me using the wrong file name.. should be gone now...

**Comment by FynnBe** [comment]
yay! imjoy collection now passes

**Comment by oeway** [comment]
> Hey, that was related to me using the wrong file name.. should be gone now...

Great that you find it out, I have no idea, maybe as an improvement in the future, let's print a better message to indicate the exact place that were wrong?

**Pull request merged**
